# Generated by Django 5.2.7 on 2025-11-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Plano')),
                ('max_automations', models.IntegerField(default=1, verbose_name='Limite de Automações')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço Mensal')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
