# Generated by Django 5.2.7 on 2025-10-06 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Automação')),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube')], max_length=20, verbose_name='Plataforma')),
                ('channel_identifier', models.CharField(max_length=100, verbose_name='Utilizador do TikTok ou ID do Canal do YouTube')),
                ('discord_webhook_url', models.URLField(max_length=500, verbose_name='URL do Webhook do Discord')),
                ('is_active', models.BooleanField(default=True, verbose_name='Automação Ativa?')),
                ('last_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='Último Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'unique_together': {('user', 'platform', 'channel_identifier')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=20, verbose_name='Status do Log')),
                ('details', models.TextField(verbose_name='Detalhes do Log')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automation')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
