# Generated by Django 5.2.7 on 2025-11-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_plan_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Plano'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='last_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=20, verbose_name='Último Status'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], max_length=20, verbose_name='Status do Log'),
        ),
    ]
