# Generated by Django 5.2.7 on 2025-11-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_userprofile_plan_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
